<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>UmaSeedInstaller.Tests</AssemblyName>
    <RootNamespace>UmaSeedInstaller.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\UmaSeedInstaller.Core\UmaSeedInstaller.Core.csproj" />
  </ItemGroup>
</Project>

